[project]
name = "ffmpeg-better-clip"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = []

[tool.ruff]
ignore = ["E402", "F401"]
src = ["src"]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
